const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Browser,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.Touch,
		C3.Plugins.TiledBg,
		C3.Behaviors.Pin,
		C3.Behaviors.Bullet,
		C3.Behaviors.Platform,
		C3.Behaviors.Sin,
		C3.Plugins.Spritefont2,
		C3.Behaviors.solid,
		C3.Behaviors.Fade,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.RotateClockwise,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.TiledBg.Cnds.CompareX,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.TiledBg.Acts.MoveToTop,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Behaviors.Platform.Acts.SetGravity,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Mouse.Cnds.IsOverObject
	];
};
self.C3_JsPropNameTable = [
	{menu_logo: 0},
	{play: 0},
	{siralama: 0},
	{Browser: 0},
	{fare: 0},
	{Audio: 0},
	{Touch: 0},
	{Pin: 0},
	{alan: 0},
	{Bullet: 0},
	{arka_plan: 0},
	{Platform: 0},
	{Sine: 0},
	{Bird: 0},
	{boru_alt: 0},
	{boru_ust: 0},
	{SpriteFont: 0},
	{Solid: 0},
	{zemin: 0},
	{Fade: 0},
	{getready: 0},
	{instruction: 0},
	{panel: 0},
	{panelOk: 0},
	{panelMenu: 0},
	{Spritehighscore: 0},
	{Spritescore: 0},
	{madalya: 0},
	{Borular: 0},
	{Butonlar: 0},
	{score: 0},
	{highscore: 0},
	{oyunDurumu: 0}
];

self.InstanceType = {
	menu_logo: class extends self.ISpriteInstance {},
	play: class extends self.ISpriteInstance {},
	siralama: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	fare: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	alan: class extends self.ITiledBackgroundInstance {},
	arka_plan: class extends self.ITiledBackgroundInstance {},
	Bird: class extends self.ISpriteInstance {},
	boru_alt: class extends self.ISpriteInstance {},
	boru_ust: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	zemin: class extends self.ITiledBackgroundInstance {},
	getready: class extends self.ISpriteInstance {},
	instruction: class extends self.ISpriteInstance {},
	panel: class extends self.ISpriteInstance {},
	panelOk: class extends self.ISpriteInstance {},
	panelMenu: class extends self.ISpriteInstance {},
	Spritehighscore: class extends self.ISpriteFontInstance {},
	Spritescore: class extends self.ISpriteFontInstance {},
	madalya: class extends self.ISpriteInstance {},
	Borular: class extends self.ISpriteInstance {},
	Butonlar: class extends self.ISpriteInstance {}
}